#!/bin/sh
#FILE_LIST=$(ls )

## This is a script that organises my files in my wiki and creates a pathfor them automatically

## This is a recursive function that goes through all the files and add them on the list




recur_fn() {
	for FILE in *; do
		if [[ -d "$FILE" ]]; then # If the file is a directory then do this
			printf "\n## [%s](%s)" "$FILE" "$(readlink -f $FILE)/$FILE.md" 1>> $1  # Create a Index File
			printf "Creating Index File for folder %s\n" "$FILE"
			( cd "$FILE"&& echo " " > "$FILE.md" && recur_fn "$FILE.md") 
			# Goes into the directroy creates an empty index file then outputs STDOUT to the index file
			#outputs STDOUT to index file
		else
			if [[ -f "$FILE" ]]; then
				if [[ "${FILE##*.}" == 'md' ]] && ! [[ "$FILE" == 'full_index.md' ]] ; then
					DIR="$(dirname $(readlink -f $FILE))"
					NAME="$( head -1 $FILE)"
					NAME="${NAME:1}"
					printf "Creating entry for file %s\n" "$FILE"
					printf "\n[%s](%s/%s)\n"  "$NAME" "$DIR" "$FILE" 1>> $1  # If md file then write it down (output on STDOUT
					
				fi
			fi
		fi
	done
	}

if [ -e "full_index.md" ]; then
	echo "Index already exists, preparing to rebuild"
	echo " " > 'full_index.md' 
else
	touch 'full_index.md'
fi


#printf "# Full Index of Wiki\n" > 'full_index.md'

recur_fn 'full_index.md'

sed -i "1s/^/# $USER's Wiki\n/" 'full_index.md'
echo "Finished Building Index"
